name: nodejs tb autosign

on: 
  push:
  gollum: 
  schedule: 
      - cron: '45 21 * * *'

jobs:
  one:

    runs-on: ubuntu-latest
    
    steps:
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: |
        npm install
    - name: node ./src/main.js
      run:  |
        node ./src/main.js
