name: nodejs

on: 
  push:
  gollum: 
  schedule: 
      - cron: '02 16 * * *'

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.139.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 打卡
          body: success
          to: 15766973191@139.com
          from: GitHub Actions
