name: nodejs

on: 
  push:
  gollum: 
  schedule: 
      - cron: '02 16 * * *'

jobs:
  one:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: |
        npm install
    - name: node ./src/main.js
      env:
        password: ${{secrets.password}}
        account: ${{secrets.account}}
        temperature: ${{secrets.temperature}}
        address: ${{secrets.address}}
      run:  |
        node ./src/main.js
