name: nodejs

on: 
  gollum: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '02 16 * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: npm install
      run: |
        npm install
    - name: node ./src/main.js
      env:
        password: ${{secrets.password}}
        account: ${{secrets.account}}
        temperature: ${{secrets.temperature}}
        address: ${{secrets.address}}
      run:  |
        node ./src/main.js

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - uses: actions/checkout@v2
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 打卡
          body: success
          to: luotongxiao@qq.com
          from: GitHub Actions
