on:
  push:
    branches: [ main ]
  schedule:
  - cron: "4 16 * * *"
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: use Node.js 10.x 
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: npm install
      run: |
         npm install 
         node ./src/main.js 
