name: nodejs start

on: 
  push:
  gollum: 
  schedule: 
      - cron: '45 21 * * *'

jobs:
  start:

    runs-on: ubuntu-latest
    
    steps:
    - name: npm install
      run: |
        npm install
    - uses: actions/checkout@v2
    - name: node ./src/main.js
      env:
        password: ${{secrets.password}}
        account: ${{secrets.account}}
        temperature: ${{secrets.temperature}}
        address: ${{secrets.address}}
      run:  |
        node ./src/main.js
