name: nodejs start

on: 
  push:
  gollum: 
  schedule: 
      - cron: '45 21 * * *'

jobs:
  start1:
    runs-on: ubuntu-latest  
    steps:
    - name: npm install
      run: |
        npm install
    - uses: actions/checkout@v2
        
  start2:
    needs: start1
    runs-on: ubuntu-latest 
    steps:
    - name: node ./src/main
      env:
        password: ${{secrets.password}}
        account: ${{secrets.account}}
        temperature: ${{secrets.temperature}}
        address: ${{secrets.address}}
      run:  |
        node ./src/main.js
